# Generated by Django 3.2.3 on 2021-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempURL',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('valid_until', models.DateTimeField()),
            ],
        ),
    ]
