# Generated by Django 3.2.3 on 2021-09-17 08:34

from django.db import migrations, models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_tempurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='id',
            field=models.CharField(editable=False, max_length=44, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='valid_until',
            field=models.DateTimeField(validators=[images.validators.valid_until_validator]),
        ),
    ]
